# CircuitPython gc module stub.
# Extends standard gc with CircuitPython-specific memory functions.

def collect() -> None: ...
def enable() -> None: ...
def disable() -> None: ...
def isenabled() -> bool: ...

# CircuitPython-specific
def mem_free() -> int:
    """Return the number of bytes of available heap RAM, or -1 if this
    information is not available."""
    ...

def mem_alloc() -> int:
    """Return the number of bytes of heap RAM allocated by Python code, or -1
    if this information is not available."""
    ...
